services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file: .env
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_PORT
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GITHUB_CALLBACK_URL
      - REDIS_URL
      - SESSION_KEY
      - SESSION_SECRET
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
        - action: rebuild
          path: ./go.mod
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    env_file: .env
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:
  go-mod:

networks:
  backend:
    driver: bridge
